language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

matrix:
  include:
    - python: 2.7
      env: PANDAS=0.19.0  MATPLOTLIB=1.5.3
    - python: 2.7
      env: PANDAS=0.22.0  MATPLOTLIB=1.5.3
    - python: 2.7
      env: PANDAS=0.22.0  MATPLOTLIB=2.1.2
    - python: 3.6
      env: PANDAS=0.19.0  MATPLOTLIB=1.5.3
    - python: 3.6
      env: PANDAS=0.22.0  MATPLOTLIB=1.5.3
    - python: 3.6
      env: PANDAS=0.22.0  MATPLOTLIB=2.1.2


before_install:
  - pip install -U pip
  - pip install wheel


install:
  - pip wheel numpy
  - pip wheel -r requirements.txt
  - pip wheel -r requirements.test.txt

  - pip install numpy
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

script:
  - py.test FlowCytometryTools/ --cov FlowCytometryTools -v --cov-report term-missing

after_success:
  - coveralls
