language: python

sudo: false

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

matrix:
  include:
    - python: 2.7
      env: PANDAS=0.16.2  MATPLOTLIB=1.3.1
    - python: 2.7
      env: PANDAS=0.17.1  MATPLOTLIB=1.4.3
    - python: 2.7
      env: PANDAS=0.18.1  MATPLOTLIB=1.5.1
    - python: 2.7
      env: PANDAS=0.19.2  MATPLOTLIB=2.0.0
    - python: 3.6
      env: PANDAS=0.22.0  MATPLOTLIB=2.1.1

before_install:
  - pip install -U pip
  - pip install wheel


install:
  - pip wheel numpy
  - pip wheel -r requirements.txt
  - pip wheel -r requirements.test.txt

  - pip install numpy
  - if [[ $MATPLOTLIB == 'master' ]]; then pip install git+https://github.com/matplotlib/matplotlib.git; else pip wheel matplotlib==$MATPLOTLIB; pip install matplotlib==$MATPLOTLIB; fi

  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

  - if [[ $PANDAS == 'master' ]]; then pip install git+https://github.com/pydata/pandas.git; else pip wheel pandas==$PANDAS; pip install pandas==$PANDAS; fi

script:
  - py.test FlowCytometryTools/ --cov FlowCytometryTools -v --cov-report term-missing

after_success:
  - coveralls
